---
services:
  pyats:
    image: ciscotestautomation/pyats:latest
    container_name: pyats
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    working_dir: "/pyats"
    volumes:
      - ./pyats:/pyats:rw
      # Mount SSH keys from host
      - ~/.ssh:/tmp/.ssh:ro
      # Mount SSH config from host
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config
    entrypoint: bash
